OUTPUT_DIR: "./logs/prw_coat"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/data1/mustansar/dataset/PRW-v16.04.20/"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 13
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
DISP_PERIOD: 100
